version: '2'

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=s3cretP4ssword123456789OverrideInPipeline
      - POSTGRES_DB=sparkpoc

